# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker CD

on:
  release:
    types: [published, created, edited]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}   
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}  
        run: |
          docker login -u $DOCKERHUB_USERNAME -p "$DOCKERHUB_TOKEN"

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        
      - name: Echo
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: docker build teams
        run: |
          docker build . -t nobedocker/teams:latest

      - name: docker push
        run: |
          docker push nobedocker/teams:latest